### ISSUE TITLE
php7

### ISSUE THREAD

**Issue by jpcsguru** [webshopapps/module-shipping-tracker#5]
does not work on php7

**Comment by wsagen** [comment]
Can you detail exactly what the error was that you saw with PHP 7? We don't see any issues with our internal testing

**Comment by jpcsguru** [comment]
it does not display links it only works on php5.6  using mag 2..1.7

**Comment by wsajason** [comment]
Can you confirm which version of PHP 7 you are using? Our extensions are tested on PHP 5.6 and PHP 7

**Comment by jpcsguru** [comment]
php7.0.21

**Comment by oviliz** [comment]
I'm using 7.1.13 and is working fine.
