### ISSUE TITLE
WebShopApps Tracker 2?

### ISSUE THREAD

**Issue by oviliz** [webshopapps/module-shipping-tracker#6]
Does anyone know how do I get a WebShopApps Tracker 2?
I'm using both Royal Mail and myHermes.

**Comment by gkruger1** [comment]
I think what oviliz means is that only WebShopApps Tracker 1 with its fields appear under Shipping Methods. WebShopApps Tracker 2 to 5 are completely missing. I have the same problem, running Magento 2.2.2.

**Comment by oviliz** [comment]
Indeed. Using CE 2.2.2 too, but looking at the code, it seems that is been designed this way on purpose (e.g. https://github.com/webshopapps/module-shipping-tracker/blob/master/src/etc/adminhtml/system.xml).

**Comment by wsagen** [comment]
We've recently created a new version of this extension under our ShipperHQ namespace. It includes support for 5 tracking carriers. You should remove the webshopapps version using composer and move to ShipperHQ 

https://github.com/shipperhq/module-shipping-tracker
